'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '@/lib/supabase'
import {councilDecision} from '@/lib/mm-intelligence'

type Product={id:string;name:string;signal_query:string;market_code:string;source_name?:string;competitor_name?:string;store_url:string;image_url:string;price?:number;cost?:number;currency?:string;verified_at:string;rating?:number;reviews?:number;sales_status?:string;opportunity_score:number;demand_score:number;momentum_score:number;commercial_score:number;sources_count:number;data_quality_pct:number;status:string}
type Ranked=Product&{council:ReturnType<typeof councilDecision>}
function Score({value}:{value:number}){const n=Math.round(value||0),c=n>=80?'#34d399':n>=60?'#fbbf24':'#fb7185';return <span style={{display:'inline-grid',placeItems:'center',width:44,height:44,borderRadius:'50%',border:`3px solid ${c}`,color:c,fontWeight:800,fontFamily:'var(--mono)'}}>{n}</span>}
function money(v?:number,c='USD'){if(v==null)return '—';try{return new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(v)}catch{return '$'+v}}

export default function RadarPage(){
 const [rows,setRows]=useState<Ranked[]>([]),[market,setMarket]=useState('US'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Ranked|null>(null)
 async function load(){setLoading(true);setError('');const {data,error}=await supabase.functions.invoke('mm-dashboard-api',{body:{action:'real-products',marketCode:market,limit:250}});if(error){setError(error.message);setRows([]);setLoading(false);return}
  const raw:Product[]=data?.products||[];const ranked=raw.map(p=>({...p,council:councilDecision({name:p.name,imageUrl:p.image_url,productUrl:p.store_url,price:p.price,cost:p.cost,currency:p.currency,reviews:p.reviews,rating:p.rating,salesStatus:p.sales_status,sourcesCount:p.sources_count,dataQualityPct:p.data_quality_pct,demandScore:p.demand_score,momentumScore:p.momentum_score,commercialScore:p.commercial_score,evidences:[{source:p.source_name,url:p.store_url,image:p.image_url,reviews:p.reviews,rating:p.rating,price:p.price,salesConfirmed:Boolean(p.sales_status&&!['UNKNOWN','NOT_AVAILABLE'].includes(p.sales_status)),verified:true}]})})).filter(p=>p.council.resolver.sellable).sort((a,b)=>b.council.score-a.council.score)
  setRows(ranked);setLoading(false)}
 useEffect(()=>{load()},[market])
 async function refresh(){setRefreshing(true);setError('');const {error}=await supabase.functions.invoke('mm-intelligent-discovery',{body:{marketCode:market}});if(error)setError('A coleta não concluiu: '+error.message);await load();setRefreshing(false)}
 const filtered=useMemo(()=>rows.filter(p=>!search||p.name.toLowerCase().includes(search.toLowerCase())||p.signal_query?.toLowerCase().includes(search.toLowerCase())),[rows,search])
 const approved=rows.filter(p=>p.council.decision==='APROVAR').length,observe=rows.filter(p=>p.council.decision==='OBSERVAR').length,avg=rows.length?Math.round(rows.reduce((s,p)=>s+p.council.score,0)/rows.length):0
 if(loading)return <div className="mm-loading"><div className="mm-spinner"/>Cérebro cruzando evidências...</div>
 return <div className="mm-fade-in">
  <div className="mm-page-header" style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'end',flexWrap:'wrap'}}><div><h1 className="mm-page-title">Radar · Conselho MM</h1><p className="mm-page-subtitle">Cérebro → Product Resolver → evidências → score final → decisão</p></div><button onClick={refresh} disabled={refreshing} style={{height:42,padding:'0 16px',border:0,borderRadius:9,background:'var(--purple)',color:'#fff',fontWeight:700}}>{refreshing?'CRUZANDO FONTES...':'ATUALIZAR E DECIDIR'}</button></div>
  <div style={{display:'flex',gap:8,marginBottom:14,flexWrap:'wrap'}}><input className="mm-search" placeholder="🔍 Buscar produto específico..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="mm-search" style={{width:170}} value={market} onChange={e=>setMarket(e.target.value)}><option value="US">🇺🇸 Estados Unidos</option><option value="MX">🇲🇽 México</option></select></div>
  {error&&<div style={{padding:12,marginBottom:14,border:'1px solid #fb7185',borderRadius:8,color:'#fb7185'}}>{error}</div>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginBottom:16}}>{[['Resolvidos',rows.length],['Aprovados',approved],['Observar',observe],['Score médio',avg]].map(([l,v])=><div className="mm-card" key={String(l)} style={{padding:14}}><div style={{fontSize:23,fontWeight:800,color:'var(--purple3)'}}>{v}</div><div style={{fontSize:10,color:'var(--text3)',textTransform:'uppercase'}}>{l}</div></div>)}</div>
  <div className="mm-card"><div className="mm-table-wrap"><table className="mm-table"><thead><tr><th>#</th><th>Produto específico</th><th>Score final</th><th>Conselho</th><th>Confiança</th><th>Demanda</th><th>Tendência</th><th>Margem</th><th>Fontes</th><th>Preço</th><th>Link</th></tr></thead><tbody>
  {!filtered.length?<tr><td colSpan={11} style={{textAlign:'center',padding:40,color:'var(--text3)'}}>Nenhum produto passou pelo Product Resolver.</td></tr>:filtered.map((p,i)=><tr key={p.id}><td>{String(i+1).padStart(2,'0')}</td><td style={{minWidth:340}}><div style={{display:'flex',gap:12,alignItems:'center'}}><img src={p.image_url} alt={p.name} onClick={()=>setSelected(p)} style={{width:68,height:68,objectFit:'contain',background:'#fff',borderRadius:9,cursor:'zoom-in'}}/><div><b>{p.name}</b><div style={{fontSize:9,color:'var(--text3)',marginTop:4}}>{p.council.reasons.join(' · ')}</div></div></div></td><td><Score value={p.council.score}/></td><td><b style={{color:p.council.decision==='APROVAR'?'#34d399':p.council.decision==='OBSERVAR'?'#fbbf24':'#fb7185'}}>{p.council.decision}</b></td><td>{p.council.confidence}%</td><td>{p.council.demand}</td><td>{p.council.trend}</td><td>{p.council.margin||'—'}</td><td>{p.council.sourceCount}</td><td>{money(p.price,p.currency)}</td><td><a href={p.store_url} target="_blank" rel="noopener noreferrer" style={{color:'#34d399',fontWeight:800}}>VER ↗</a></td></tr>)}
  </tbody></table></div></div>
  <div style={{padding:12,marginTop:12,background:'var(--card)',border:'1px solid var(--border)',borderRadius:9,fontSize:11,color:'var(--text3)'}}>Regra dura: sem produto específico + foto real + link direto, não entra. Uma única fonte limita a nota. APROVAR exige score ≥80, confiança suficiente e pelo menos 3 fontes independentes.</div>
  {selected&&<div onClick={()=>setSelected(null)} style={{position:'fixed',inset:0,zIndex:2000,background:'rgba(0,0,0,.86)',display:'grid',placeItems:'center',padding:20}}><div className="mm-card" onClick={e=>e.stopPropagation()} style={{width:'min(820px,96vw)',padding:16}}><img src={selected.image_url} alt={selected.name} style={{width:'100%',height:'60vh',objectFit:'contain',background:'#fff',borderRadius:10}}/><h3>{selected.name}</h3><p style={{color:'var(--text3)'}}>Conselho: {selected.council.decision} · Score {selected.council.score} · Confiança {selected.council.confidence}%</p></div></div>}
 </div>}
