'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { supabase } from '../lib/supabase'

function Ring({ score, size = 48 }: { score:number; size?:number }) {const r=(size-6)/2,circ=2*Math.PI*r,fill=(Math.min(score,100)/100)*circ,color=score>=80?'#f59e0b':score>=65?'#10b981':score>=45?'#fcd34d':'#ef4444';return <div style={{position:'relative',width:size,height:size,flexShrink:0}}><svg width={size} height={size} style={{transform:'rotate(-90deg)'}}><circle cx={size/2} cy={size/2} r={r} fill="none" stroke="rgba(255,255,255,.06)" strokeWidth="3.5"/><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth="3.5" strokeDasharray={fill+' '+circ} strokeLinecap="round"/></svg><span style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',fontSize:size>40?13:11,fontWeight:800,color,fontFamily:'var(--mono)'}}>{score}</span></div>}
function TimingBadge({t}:{t:string}){const key=(t||'').replace(/ .*/g,'')||'AMARELO';const cfg:any={OURO:['🥇 OURO','#f59e0b'],VERDE:['✅ VERDE','#10b981'],AMARELO:['⚠ AMARELO','#fcd34d'],VERMELHO:['❌ VERM.','#ef4444']};const c=cfg[key]||cfg.AMARELO;return <span style={{color:c[1],border:`1px solid ${c[1]}30`,borderRadius:6,padding:'3px 8px',fontSize:11,fontWeight:700,fontFamily:'var(--mono)',whiteSpace:'nowrap'}}>{c[0]}</span>}
function StatusBadge({s}:{s:string}){const color=s==='winner'?'#10b981':s==='testing'?'#f59e0b':s==='new'?'#a78bfa':'#9ca3af';return <span style={{color,border:`1px solid ${color}30`,borderRadius:6,padding:'3px 8px',fontSize:11,fontWeight:600,textTransform:'uppercase',fontFamily:'var(--mono)'}}>{s||'—'}</span>}
const EMOJI:any={Eyes:'👁',Pain:'💊',Skin:'✨',Hair:'💆',Nails:'💅',Sleep:'😴',Beauty:'💄',Posture:'🦾',Massage:'💆'}
function metaLink(p:any){return p.advertiser_page_id?`https://www.facebook.com/ads/library/?view_all_page_id=${p.advertiser_page_id}&active_status=active&ad_type=all&country=US&media_type=video`:`https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=US&q=${encodeURIComponent(p.name)}&search_type=keyword_unordered&media_type=video`}

export default function Dashboard(){
 const [products,setProducts]=useState<any[]>([]),[alerts,setAlerts]=useState<any[]>([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState('all'),[now,setNow]=useState(''),[manual,setManual]=useState<Record<string,string>>({})
 useEffect(()=>{setNow(new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}));Promise.all([supabase.from('ranking_view').select('*').limit(20),supabase.from('alerts').select('*').order('created_at',{ascending:false}).limit(5)]).then(([{data:p},{data:a}])=>{if(p)setProducts(p);if(a)setAlerts(a);setLoading(false)})},[])
 async function validateManual(p:any){if(manual[p.id]==='loading'||manual[p.id]==='done')return;setManual(x=>({...x,[p.id]:'loading'}));const {data,error}=await supabase.functions.invoke('mm-manual-validate',{body:{product:p.name,productId:p.id,marketCode:'US'}});if(error||!data?.ok){setManual(x=>({...x,[p.id]:'error'}));return}setManual(x=>({...x,[p.id]:'done'}))}
 if(loading)return <div style={{display:'flex',justifyContent:'center',padding:80,color:'var(--text3)',fontFamily:'var(--mono)'}}>Carregando dados...</div>
 const filtered=products.filter(p=>filter==='ouro'?p.timing?.includes('OURO'):filter==='verde'?p.timing?.includes('VERDE'):filter==='winner'?p.status==='winner':filter==='mx'?p.mx_compatible:true)
 const gold=products.filter(p=>p.timing?.includes('OURO')).length,green=products.filter(p=>p.timing?.includes('VERDE')).length,winners=products.filter(p=>p.status==='winner').length,avg=products.length?Math.round(products.reduce((s,p)=>s+(p.score_final||0),0)/products.length):0,highAds=products.filter(p=>(p.n_ads||0)>=40).length
 const cards=[['Total Produtos',products.length,'#a78bfa','all'],['Timing Ouro',gold,'#f59e0b','ouro'],['Timing Verde',green,'#10b981','verde'],['Vencedores',winners,'#34d399','winner'],['Score Médio',avg,'#60a5fa','all'],['40+ Anúncios',highAds,'#c084fc','all']] as const
 return <div style={{paddingBottom:32}}>
  <div style={{marginBottom:24,display:'flex',justifyContent:'space-between',alignItems:'flex-end',flexWrap:'wrap',gap:8}}><div><h1 style={{fontSize:22,fontWeight:800,color:'var(--text)',margin:0}}>MM Intelligence</h1><p style={{fontSize:12,color:'var(--text3)',margin:'4px 0 0',fontFamily:'var(--mono)'}}>Score MM · IA Analista · Timing de Entrada</p></div><div style={{fontSize:11,color:'var(--text3)',fontFamily:'var(--mono)',textTransform:'capitalize'}}>{now}</div></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:8,marginBottom:20}}>{cards.map(([label,val,color,key])=><button key={label} onClick={()=>setFilter(key)} title={`Clique para ver os produtos de ${label}`} style={{background:filter===key?'rgba(124,58,237,.12)':'var(--card)',border:filter===key?'1px solid var(--purple3)':'1px solid var(--border)',borderRadius:10,padding:'14px 12px',textAlign:'center',cursor:'pointer'}}><div style={{fontSize:26,fontWeight:900,color,fontFamily:'var(--mono)',lineHeight:1}}>{val}</div><div style={{fontSize:10,color:'var(--text3)',marginTop:5,fontFamily:'var(--mono)',textTransform:'uppercase'}}>{label}</div><div style={{fontSize:9,color:'var(--purple3)',marginTop:5,fontFamily:'var(--mono)'}}>ver produtos →</div></button>)}</div>
  <div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:12,marginBottom:16,overflow:'hidden'}}>
   <div style={{display:'flex',justifyContent:'space-between',padding:'16px 20px',borderBottom:'1px solid var(--border)'}}><span style={{fontSize:14,fontWeight:700,color:'var(--text)'}}>Ranking de Produtos</span><Link href="/produtos" style={{fontSize:11,color:'var(--purple3)',textDecoration:'none'}}>Ver todos →</Link></div>
   <div style={{display:'flex',gap:6,padding:'12px 20px',borderBottom:'1px solid var(--border)',flexWrap:'wrap'}}>{[['all','Todos'],['ouro','🥇 Ouro'],['verde','✅ Verde'],['winner','🏆 Winner'],['mx','🇲🇽 MX']].map(([k,v])=><button key={k} onClick={()=>setFilter(k)} style={{background:filter===k?'var(--purple)':'transparent',color:filter===k?'#fff':'var(--text3)',border:'1px solid var(--border)',borderRadius:6,padding:'5px 12px',fontSize:11,cursor:'pointer'}}>{v}</button>)}</div>
   <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['#','Produto','Score','Timing','Nicho','Fonte','Ads','CPA','Margem','Status','Ação','Links'].map(h=><th key={h} style={{padding:'10px 12px',textAlign:'left',fontSize:10,color:'var(--text3)',fontFamily:'var(--mono)',textTransform:'uppercase'}}>{h}</th>)}</tr></thead><tbody>
    {filtered.map((p,i)=><tr key={p.id} style={{borderTop:'1px solid var(--border)'}}>
     <td style={{padding:'10px 12px',fontFamily:'var(--mono)',fontSize:11,color:'var(--text3)'}}>{String(i+1).padStart(2,'0')}</td>
     <td style={{padding:'10px 12px',minWidth:220}}><Link href={'/produtos/'+p.id} style={{display:'flex',alignItems:'center',gap:10,textDecoration:'none'}}>{p.image_url?<img src={p.image_url} alt={p.name} style={{width:36,height:36,borderRadius:8,objectFit:'cover'}}/>:<div style={{width:36,height:36,borderRadius:8,background:'var(--bg3)',display:'flex',alignItems:'center',justifyContent:'center'}}>{EMOJI[p.niche]||'🌿'}</div>}<div><div style={{fontWeight:700,color:'var(--text)',fontSize:13}}>{p.name}</div><div style={{fontSize:11,color:'var(--text3)'}}>{p.name_es}</div></div></Link></td>
     <td style={{padding:'10px 12px'}}><Link href={'/produtos/'+p.id} title="Abrir composição do Score" style={{display:'inline-block',textDecoration:'none',cursor:'pointer'}}><Ring score={Math.round(p.score_final||0)} size={44}/></Link></td>
     <td style={{padding:'10px 12px'}}><TimingBadge t={p.timing}/></td><td style={{padding:'10px 12px',fontSize:11,color:'#a78bfa'}}>{p.niche}</td><td style={{padding:'10px 12px',fontSize:10,color:'var(--text3)'}}>{p.source}</td><td style={{padding:'10px 12px',fontFamily:'var(--mono)'}}>{p.n_ads||'—'}</td><td style={{padding:'10px 12px',fontFamily:'var(--mono)',color:'#34d399'}}>{p.cpa_ideal?'$'+p.cpa_ideal:'—'}</td><td style={{padding:'10px 12px',fontFamily:'var(--mono)'}}>{p.margin_pct?p.margin_pct.toFixed(1)+'%':'—'}</td><td style={{padding:'10px 12px'}}><StatusBadge s={p.status}/></td>
     <td style={{padding:'10px 12px'}}><button onClick={()=>validateManual(p)} disabled={manual[p.id]==='loading'||manual[p.id]==='done'} title="Sua decisão valida o produto e dispara o pacote completo" style={{minWidth:112,padding:'7px 9px',borderRadius:7,border:'1px solid rgba(52,211,153,.45)',background:manual[p.id]==='done'?'rgba(52,211,153,.18)':'rgba(52,211,153,.08)',color:manual[p.id]==='error'?'#fb7185':'#34d399',fontSize:10,fontWeight:800,cursor:'pointer'}}>{manual[p.id]==='loading'?'PROCESSANDO...':manual[p.id]==='done'?'✓ VALIDADO':manual[p.id]==='error'?'TENTAR NOVAMENTE':'☐ VALIDAR MANUAL'}</button></td>
     <td style={{padding:'10px 12px'}}><div style={{display:'flex',gap:4}}><a href={metaLink(p)} target="_blank" rel="noopener noreferrer" style={{color:'#60a5fa',fontSize:11,textDecoration:'none'}}>Meta</a><a href={`https://www.tiktok.com/search?q=${encodeURIComponent(p.name)}&type=video`} target="_blank" rel="noopener noreferrer" style={{color:'#f472b6',fontSize:11,textDecoration:'none'}}>TT</a></div></td>
    </tr>)}
   </tbody></table></div>
  </div>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
   <div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:12,overflow:'hidden'}}><div style={{padding:'14px 18px',borderBottom:'1px solid var(--border)',fontWeight:700,color:'var(--text)'}}>Alertas</div>{alerts.length===0?<div style={{padding:24,color:'var(--text3)'}}>Nenhum alerta ainda</div>:alerts.map(a=><div key={a.id} style={{padding:'10px 18px',borderBottom:'1px solid var(--border)'}}><div style={{fontSize:13,fontWeight:600,color:'var(--text)'}}>{a.title}</div><div style={{fontSize:11,color:'var(--text3)',marginTop:3}}>{a.message}</div></div>)}</div>
   <div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:12,overflow:'hidden'}}><div style={{padding:'14px 18px',borderBottom:'1px solid var(--border)',fontWeight:700,color:'var(--text)'}}>Janelas de Oportunidade</div>{products.filter(p=>p.window_mx_days>0).sort((a,b)=>a.window_mx_days-b.window_mx_days).slice(0,5).map(p=><Link key={p.id} href={'/produtos/'+p.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 18px',borderBottom:'1px solid var(--border)',textDecoration:'none'}}><div><div style={{fontSize:13,fontWeight:600,color:'var(--text)'}}>{p.name}</div><div style={{fontSize:11,color:'var(--text3)',fontFamily:'var(--mono)'}}>MX · {p.window_mx_days} dias restantes</div></div><TimingBadge t={p.timing}/></Link>)}</div>
  </div>
 </div>
}